name: build

on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 */2 * * *' # every two hours.
    #- cron: '0 0 17 * *' # every month, the 17th day.

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: windows-10
    #      - name: windows-11
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Log the available disk space, so we can inspect it later.
      # NB GitHub-hosted runners have limited available disk space.
      #    see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
      - name: Show available disk space before build
        run: Get-PSDrive -PSProvider FileSystem

      # NB we are writing outside of the current working/job directory
      #    because it does not have sufficient available disk space.
      - name: Build
        run: pwsh uup-dump-get-windows-iso.ps1 ${{ matrix.name }} c:/output

      - name: Show available disk space after build
        run: Get-PSDrive -PSProvider FileSystem

      - name: Build summary
        id: build_summary
        run: |
          $iso = Get-Content (Resolve-Path c:/output/*.json) | ConvertFrom-Json
          Add-Content $env:GITHUB_STEP_SUMMARY @"
          | Property | Value |
          | :--- | :--- |
          | Name | $($iso.name) |
          | Build | $($iso.build) |
          | Checksum | $($iso.checksum) |
          $($iso.images | ForEach-Object {"| Image Name #$($_.index) | $($_.name) |"})
          | UUP dump | [$($iso.title)]($($iso.uupDump.downloadUrl)) |
          "@
          echo "::set-output name=build::$(echo $iso.build)"
          echo "::set-output name=name::$(echo $iso.name)"
          echo "::set-output name=title::$(echo $iso.title)"
          echo "::set-output name=iso_name::$(echo $iso.name)"

      - name: Compress ISO into multipart zip
        run: |
          $isoName = "${{ steps.build_summary.outputs.iso_name }}"
          7z a -v1g "c:/output/$isoName.7z" c:/output/*.iso

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build_summary.outputs.build }}_${{ github.run_number }}
          release_name: ${{ steps.build_summary.outputs.name }}
          body: ${{ steps.build_summary.outputs.title }}
          draft: false
          prerelease: false

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: c:/output/${{ steps.build_summary.outputs.iso_name }}*.7z
      - name: Find split parts
        id: find_parts
        run: |
          $isoName = "${{ steps.build_summary.outputs.iso_name }}"
          $files = Get-ChildItem -Path "c:/output/$isoName*.7z.*"
          $filePaths = $files | ForEach-Object { $_.FullName }
          echo "::set-output name=files::$(echo $filePaths -join ',')"

      - name: Install GitHub CLI
        run: |
          Invoke-WebRequest -Uri https://github.com/cli/cli/releases/download/v2.0.0/gh_2.0.0_windows_amd64.msi -OutFile ghcli.msi
          Start-Process msiexec.exe -ArgumentList '/i ghcli.msi /quiet /norestart' -NoNewWindow -Wait
          Remove-Item ghcli.msi

      - name: Upload split parts to Release
        run: |
          $files = '${{ steps.find_parts.outputs.files }}'.Split(',')
          foreach ($file in $files) {
            & gh release upload ${{ steps.create_release.outputs.upload_url }} $file --repo ${{ github.repository }}
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
